name: "Vivado BD Mermaid"
description: "Generate Mermaid diagrams from Vivado IP Integrator Block Design (BD) Tcl exports and optionally update README."
author: "AdakHaddad"
inputs:
  repo-root:
    description: "Repository root (usually .)"
    required: false
    default: "."
  out-dir:
    description: "Output directory for generated .mmd files"
    required: false
    default: "docs/bd"
  readme:
    description: "README file to update"
    required: false
    default: "README.md"
  args:
    description: "Extra args passed to the generator script (e.g. --axi-edge-labels kind)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Generate Mermaid diagrams
      shell: bash
      run: |
        set -euo pipefail
        python "${{ github.action_path }}/bd_tcl_to_mermaid.py" \
          --repo-root "${{ inputs.repo-root }}" \
          --out-dir "${{ inputs.out-dir }}" \
          --readme "${{ inputs.readme }}" \
          ${{ inputs.args }}
